{
 "title": "RK_MODA2",
 "time": { "from": "2020-12-01T00:00:00.000Z", "to": "2024-10-01T00:00:00.000Z" },
 "panels": [
  { "title": "RKMODA", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "\n\n<div\n  style=\"\n    background-color: #F48FB1;\n    color: white;\n    font-size: 50px;\n    text-align: center;\n    padding: 45px;\n    font-family: 'Playfair Display', serif;\n    font-weight: 700;\n  \"\n\n>\n  RK MODA FEMININA\n</div>"
   }
  },
  {
   "title": "Total de Pedidos",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "moda femm",
     "rawSql": "SELECT COUNT(distinct(id_pedido)) AS total_pedidos FROM fato_pedidos\r\nORDER BY total_pedidos"
    }
   ]
  },
  {
   "title": "Pedidos nos últimos 30 Dias",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "rk moda",
     "rawSql": "SELECT COUNT(DISTINCT(ID_PEDIDO)) AS total_pedidos_30dias\r\nFROM fato_pedidos\r\nWHERE data_pedido >= CURRENT_DATE - INTERVAL '30 days';\r\n"
    }
   ]
  },
  {
   "title": "Faturamento Médio dos Últimos 30 Dias",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "rk moda",
     "rawSql": "SELECT * FROM faturamentomedio_30dias LIMIT 50 "
    }
   ]
  },
  {
   "title": "Faturamento do Mês Atual ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "rk moda",
     "rawSql": "SELECT mes, SUM(faturamento) FROM  Faturamento_12meses \r\nGROUP BY 1\r\nORDER BY\r\n    CAST(SUBSTRING(mes FROM '(\\d{4})') AS INTEGER) DESC, \r\n    CAST(SUBSTRING(mes FROM 'M(\\d+)') AS INTEGER) DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Faturamento / Últimos 15 dias",
   "type": "stat",
   "description": "Distribuição de pedidos por cidade",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "moda femm",
     "rawSql": "SELECT * FROM faturamento_15dias \r\n"
    }
   ]
  },
  {
   "title": "Faturamento nos últimos 12 meses",
   "type": "barchart",
   "gridPos": { "h": 15, "w": 15, "x": 0, "y": 11 },
   "targets": [
    {
     "dataset": "rk moda",
     "rawSql": "SELECT mes, SUM(faturamento) FROM  Faturamento_12meses \r\nGROUP BY 1\r\nORDER BY\r\n    CAST(SUBSTRING(mes FROM '(\\d{4})') AS INTEGER), \r\n    CAST(SUBSTRING(mes FROM 'M(\\d+)') AS INTEGER);"
    }
   ]
  },
  {
   "title": "Formas de Pagamento",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 5, "x": 15, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "rk moda",
     "rawSql": "SELECT\r\n  CASE\r\n    WHEN forma_pagamento IN ('Mercado Pago', 'Mercado Pago Checkout PRO') THEN 'Mercado Pago'\r\n    WHEN forma_pagamento = 'Pix' THEN 'Pix'\r\n  END AS \"Forma de Pagamento\",\r\n  COUNT(*) AS \"Qtd de Pedidos\"\r\nFROM formapagamento_30dias\r\nWHERE forma_pagamento IN ('Mercado Pago', 'Mercado Pago Checkout PRO', 'Pix')\r\nGROUP BY 1;\r\n"
    }
   ]
  },
  {
   "title": "5 Maiores Concentrações de Clientes por Estado",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 4, "x": 20, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "rk moda",
     "rawSql": "SELECT c.estado_cliente, COUNT(*)AS numero_clientes\r\nFROM fato_clientes c\r\nWHERE c.estado_cliente IS NOT NULL\r\nGROUP BY c.estado_cliente\r\nORDER BY numero_clientes DESC\r\nLIMIT 5"
    }
   ]
  },
  {
   "title": "Previsão Faturamento - Próximo Semestre",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 26 },
   "targets": [
    { "dataset": "rk moda", "rawSql": "select * FROM tabela_previsao " }
   ]
  },
  {
   "title": "Formas de Envio nos Últimos 30 Dias",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "rk moda",
     "rawSql": "SELECT * FROM formasenvio_30dias "
    }
   ]
  },
  {
   "title": " Top 10 clientes que mais gastaram no total",
   "type": "table",
   "gridPos": { "h": 12, "w": 15, "x": 0, "y": 36 },
   "targets": [
    {
     "dataset": "moda femm",
     "rawSql": "SELECT\r\n  c.nome_cliente,\r\n  SUM(CAST(p.valor_subtotal_pedido AS numeric)) AS total_faturamento,\r\n  COUNT(p.id_pedido)                    AS total_pedidos\r\nFROM fato_pedidos p\r\nJOIN fato_clientes c\r\n  ON p.id_cliente = c.id_cliente\r\nWHERE p.situacao_pedido <> 'Pedido Cancelado'\r\n  AND p.data_pedido >= CURRENT_DATE - INTERVAL '30 days'\r\nGROUP BY\r\n  c.nome_cliente\r\nORDER BY\r\n  total_pedidos DESC\r\nLIMIT 10;\r\n"
    }
   ]
  },
  {
   "title": "Pedidos cancelados X Pedidos enviados",
   "type": "piechart",
   "description": "Porcentagem por Situação do Pedido",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "moda femm",
     "rawSql": "SELECT \r\n    p.situacao_pedido\r\n    ,count(p.id_pedido) as quantidade_pedido\r\nFROM fato_pedidos p\r\nJOIN fato_produtos pd ON p.id_produto = pd.id_produto\r\nwhere situacao_pedido in ('Pedido Cancelado', 'Pedido Enviado')\r\nGROUP BY 1\r\n"
    }
   ]
  },
  {
   "title": "Situação de Pedido por Forma de Pagamento",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 15, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "rk moda",
     "rawSql": "SELECT * FROM situacaopedido_pagamento \r\nWHERE forma_pagamento <> 'Mercado Pago Checkout PRO'"
    }
   ]
  },
  {
   "title": "Vendas por Faixa Etária",
   "type": "table",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 48 },
   "targets": [
    {
     "dataset": "rk moda",
     "rawSql": "SELECT * FROM vendasfaixaetaria "
    }
   ]
  },
  {
   "title": "Ticket Médio nos últimos 12 meses",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 15, "x": 0, "y": 60 },
   "targets": [
    {
     "dataset": "rk moda",
     "rawSql": "SELECT * FROM FaturamentoMedio_12meses "
    }
   ]
  },
  {
   "title": "Pedidos cancelados X Pedidos enviados",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 9, "x": 15, "y": 60 },
   "targets": [
    {
     "dataset": "rk moda",
     "rawSql": "SELECT\r\n  date_trunc('month', p.data_pedido)     AS time,\r\n  COUNT(*) FILTER (WHERE p.situacao_pedido = 'Pedido Enviado')   AS pedidos_enviados,\r\n  COUNT(*) FILTER (WHERE p.situacao_pedido = 'Pedido Cancelado') AS pedidos_cancelados\r\nFROM fato_pedidos p\r\nWHERE p.data_pedido BETWEEN $__timeFrom() AND $__timeTo()\r\nGROUP BY 1\r\nORDER BY 1\r\n"
    }
   ]
  },
  {
   "title": "Top 10 Produtos",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 73 },
   "targets": [
    { "dataset": "rk moda", "rawSql": "SELECT * FROM  top10produtos " }
   ]
  },
  {
   "title": "Top 10 Produtos - Últimos 30 dias",
   "type": "table",
   "gridPos": { "h": 13, "w": 7, "x": 8, "y": 73 },
   "targets": [
    {
     "dataset": "rk moda",
     "rawSql": "SELECT * FROM  top10produtos_30dias "
    }
   ]
  },
  {
   "title": "Histórico de Semanal",
   "type": "stat",
   "description": "Última semana X Penúltima Semana ",
   "gridPos": { "h": 13, "w": 9, "x": 15, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "rk moda",
     "rawSql": "SELECT resumo FROM relatorio_semanal"
    }
   ]
  },
  { "title": "Analise de Mercado", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 87 },
   "options": {
    "content": "\n<div\n  style=\"\n    background-color: #03045e;;\n    color: white;\n    font-size: 50px;\n    text-align: center;\n    padding: 45px;\n    font-family: 'Montserrat', sans-serif;\nfont-weight: 800;\n\n\n\n  \"\n>\n  ANÁLISE DE MERCADO\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 92 },
   "options": {
    "content": "\n<div\n  style=\"\n    background-color: #00A8FF;;\n    color: white;\n    font-size: 50px;\n    text-align: center;\n    padding: 45px;\n    font-family: 'Montserrat', sans-serif;\nfont-weight: 800;\n\n\n\n  \"\n>\n  Moda Brasileira\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 92 },
   "options": {
    "content": "\n<div\n  style=\"\n    background-color: #00A8FF;;\n    color: white;\n    font-size: 50px;\n    text-align: center;\n    padding: 45px;\n    font-family: 'Montserrat', sans-serif;\nfont-weight: 800;\n\n\n\n  \"\n>\n  Shein\n</div>"
   }
  },
  {
   "title": "Total de Pedidos (Moda Brasileira)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 97 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "rk moda",
     "rawSql": "SELECT COUNT(*) AS total_pedidos\r\nFROM fato_pedidos_modabrasileira;\r\n"
    }
   ]
  },
  {
   "title": "Ticket Médio Geral (Moda Brasileira)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 6, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "rk moda",
     "rawSql": "SELECT ROUND(AVG(ticket_medio)::numeric, 2) AS ticket_medio\r\nFROM fato_pedidos_modabrasileira;\r\n"
    }
   ]
  },
  {
   "title": "Total de Produtos (SHEIN)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 97 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "rk moda",
     "rawSql": "SELECT COUNT(*) AS total_produtos\r\nFROM fato_shein;"
    }
   ]
  },
  {
   "title": "Preço Médio dos Produtos (SHEIN)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "rk moda",
     "rawSql": "SELECT ROUND(AVG(price_brl)::numeric, 2) AS preco_medio FROM fato_shein;\r\n"
    }
   ]
  },
  {
   "title": "Estados com Maior Faturamento  (Moda Brasileira)",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 102 },
   "targets": [
    {
     "dataset": "rk moda",
     "rawSql": "SELECT\r\n  estado,\r\n  SUM(valor_total) AS faturamento_total\r\nFROM fato_pedidos_modabrasileira\r\nGROUP BY estado\r\nORDER BY faturamento_total DESC;\r\n"
    }
   ]
  },
  {
   "title": "Categorias de produtos no catálogo (SHEIN)",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 102 },
   "targets": [
    {
     "dataset": "rk moda",
     "rawSql": "SELECT\r\n  convert_from(\r\n    convert_to(s.categoria, 'LATIN1'),\r\n    'UTF8'\r\n  ) AS categoria_corrigida,\r\n  COUNT(*) AS total\r\nFROM fato_shein s\r\nWHERE s.categoria <> 'outras'\r\nGROUP BY 1\r\nORDER BY total DESC\r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Receita por categoria de produto (Moda Brasileira)",
   "type": "table",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 114 },
   "targets": [
    {
     "dataset": "moda femm",
     "rawSql": "SELECT\r\n  RANK() OVER (ORDER BY SUM(f.valor_total_pedido) DESC) || 'º' AS posicao,\r\n  p.categoria,\r\n  TO_CHAR(SUM(f.valor_total_pedido), 'FM\"R$\" 999G999G999D99') AS receita\r\nFROM fato_pedidos f\r\nJOIN fato_produtos p ON f.id_produto = p.id_produto\r\nGROUP BY p.categoria\r\nORDER BY SUM(f.valor_total_pedido) DESC\r\nLIMIT 10;\r\n"
    }
   ]
  },
  {
   "title": "Distribuição de Preços (SHEIN)",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 114 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "rk moda",
     "rawSql": "SELECT\r\n  CASE\r\n    WHEN price_brl < 50    THEN '< R$50'\r\n    WHEN price_brl < 100   THEN 'R$50–99'\r\n    WHEN price_brl < 200   THEN 'R$100–199'\r\n    ELSE '>= R$200'\r\n  END                AS faixa_preco,\r\n  COUNT(*)           AS produtos_na_faixa\r\nFROM fato_shein \r\nGROUP BY faixa_preco\r\nORDER BY faixa_preco;\r\n"
    }
   ]
  },
  {
   "title": "Média de itens por estado (Moda Brasileira)",
   "type": "table",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 126 },
   "targets": [
    {
     "dataset": "moda femm",
     "rawSql": "SELECT\r\n  estado AS \"Estado\",\r\n  COUNT(qtd_itens) AS \"Soma dos Itens\"\r\nFROM fato_pedidos_modabrasileira\r\nGROUP BY estado\r\nORDER BY \"Soma dos Itens\" DESC;\r\n"
    }
   ]
  }
 ]
}